services:
  artalk:
    image: artalk/artalk-go
    container_name: artalk
    ports:
      - 9999:23366
    environment:
      TZ: Asia/Shanghai
      ATK_LOCALE: zh-CN
      ATK_SITE_DEFAULT: 游钓四方的博客
      ATK_SITE_URL: https://blog.lhasa.icu
    volumes:
      - ./data:/data

  app:
    image: node:lts
    ports:
      - 4321:4321
    working_dir: /app
    volumes:
      - ./:/app
    command: /bin/sh -c "npm install && npm run build && npm run preview -- --host 0.0.0.0"